### ISSUE TITLE
Research Financial APIs

### ISSUE THREAD

**Issue by aramedis** [rishibajaj/Financial-Indices#7]
Find 1-2 alternative free API sources to populate our HUB page

**Comment by Pedrobe9** [comment]
Messari provides a free API for crypto prices, market data metrics, on-chain metrics, and qualitative information (asset profile).
https://messari.io/api/docs

**Comment by naomimardon** [comment]
https://finnhub.io/ gives real-time WebSocket and RESTful APIs for stock data, cryptocurrencies, and fiat currencies.

**Comment by Pedrobe9** [comment]
Accessing Messary API :   https://data.messari.io/api/v1/assets
Asset profiles are free to use with attribution and link to http://messari.io/ as per our [terms of service]

**Comment by Pedrobe9** [comment]
Two API found, both placed in comments.
